module Delude where

open import Agda.Primitive public

open import Delude.Function public
open import Delude.Equality public
open import Delude.Bool public
open import Delude.Vec public
open import Delude.Functor public
open import Delude.Applicative public
open import Delude.Monad public
open import Delude.Semiring public
open import Delude.Ring public
open import Delude.Num public
open import Delude.Neg public
open import Delude.Divisible public
open import Delude.Nat public
open import Delude.Identity public
open import Delude.Const public
open import Delude.Lens public
open import Delude.Unit public
open import Delude.State public
open import Delude.Product public
open import Delude.List public
open import Delude.Option public
open import Delude.Word public
open import Delude.Contravariant public
open import Delude.Bimap public
open import Delude.Profunctor public
open import Delude.Eq public
open import Delude.Ord public
open import Delude.Unit public
open import Delude.Empty public
open import Delude.Equality public
open import Delude.Negation public
open import Delude.Semigroup public
open import Delude.Monoid public
open import Delude.Sequence public
open import Delude.String public
open import Delude.Char public
open import Delude.IO public
